server:
  port: 5003

spring:
  application:
    name: SUBMISSION-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/task_submission_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: a0d0min9@gmail.com
    password: mcgl clcp lryc tyev
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
